// import { Gabarito } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import { Toaster } from 'react-hot-toast'

// const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MainLayout>
      <Toaster position="bottom-right" />
      {children}
    </MainLayout>
  );
}
